allowBuilds:
  "@prisma/engines": true
  "@prisma/client": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - framer-motion@13.4.2
  - motion-dom@13.4.2
